version: "3"
services:
  app:
    build: .
    tty: true
    command: node /app/index.js "/input/__INPUT__"
    environment:
      - CONTAINER_NAME=docker-app-pdf-to-crop-svg-app
      - LOCAL_VOLUMN_PATH=/input/
      - RUN_COMMAND=node /app/index.js
    volumes: 
      - ./app:/app/
      - ./cache:/cache/
      - __SOURCE__:/input/
      - __SOURCE__:/output/